### ISSUE TITLE
react link context error

### ISSUE THREAD

**Issue by cybox01201** [softengKing/react-setas-business#1]
Hello. everyone.
I've some link context as below.
 <a
         className="col-2"
         href={user.infoLink}
         key={user.infoLink}
         style={{ flexGrow: 1 }}
   >
                <img
                  className="padding--md"
                  src={user.image}
                  alt={user.caption}
                  title={user.caption}
                  style={{
                    maxHeight: 128,
                    width: 128,
                  }}
               />
  </a>
But href context error keeps to occur. How I need to fix for this issue?
Thanks for your advance!

**Comment by SiriusA015** [comment]
You need to add some ref config setting.
For instance.. 
<a
      tw="flex justify-center items-center"
      href={assetInfo?.owner?.discord}
      target="_blank"
      rel="noreferrer"
>
                          <img
                            src={DiscordWhite}
                            alt="ada handle"
                            tw="md:w-6 sm:w-5 w-4 md:h-6 sm:h-5 h-4"
                          />
</a>

**Comment by cybox01201** [comment]
> commented
